[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1.26.1"]

[tool.hatch.metadata]
allow-direct-references = true
[project]
authors = [{ name = "Casey Schneider-Mizell", email = "caseysm@gmail.com" }]
dependencies = [
    "caveclient>=7.6.0",
    "cloud-files>=5.8.0",
    "cloud-volume>=11.1.5",
    "matplotlib>=3.10.6",
    "morphsync @ git+https://github.com/bdpedigo/morphsync.git@main",
    "numpy>=2.0.2",
    "orjson>=3.10.15",
    "scipy>=1.15",
    "trimesh[easy]>=4.6.2",
]
description = "Mesh and skeleton analysis"
name = "ossify"
readme = "README.md"
requires-python = ">=3.11"
version = "0.0.1"

classifiers = ["License :: OSI Approved :: MIT License"]

[project.optional-dependencies]
legacy = ["h5py>=3.14.0"]

[dependency-groups]
dev = ["bump-my-version", "cloud-volume", "ipykernel", "pytest", "pytest-cov"]
docs = ["mkdocs", "mkdocs-material", "mkdocstrings[python]"]
lint = ["ruff"]
profile = ["pyinstrument", "scalene"]
viz = ["pyvista", "seaborn>=0.13.2"]


[tool.uv]
default-groups = ["dev", "docs", "lint", "profile", "viz"]

[tool.bumpversion]
allow_dirty = false
commit = true
commit_args = ""
current_version = "0.0.1"
ignore_missing_version = false
message = "v{new_version}"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
post_commit_hooks = ["./.bmv-post-commit.sh"]
pre_commit_hooks = ['git add uv.lock', 'uv sync']
regex = false
serialize = ["{major}.{minor}.{patch}"]
sign_tags = false
tag = true
tag_message = "Bump version: {current_version} → {new_version}"
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "src/ossify/__init__.py"
replace = "__version__ = \"{new_version}\""
search = "__version__ = \"{current_version}\""

[[tool.bumpversion.files]]
filename = "pyproject.toml"
replace = "version = \"{new_version}\""
search = "version = \"{current_version}\""

[tool.ruff]
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["E9", "F63", "F7", "F82"]

[tool.poe.tasks.drybump]
cmd = "uv run bump-my-version bump --dry-run --verbose"
help = "Dry run of version bump for the project. Use with 'patch', 'minor', or 'major' to specify the version change."

[tool.poe.tasks.bump]
cmd = "uv run bump-my-version bump"
help = "Bump the version number in the project. Use with 'patch', 'minor', or 'major' to specify the version change."

[tool.poe.tasks.test]
cmd = "uv run pytest --cov=ossify tests"
help = "Run pytest with code coverage."

[tool.poe.tasks.doc-preview]
cmd = "uv run mkdocs serve"
help = "Preview documentation build locally"

[tool.poe.tasks.profile-all]
cmd = "uv run scalene"
help = "Profile cpu and memory of task with scalene"

[tool.poe.tasks.profile]
cmd = "uv run pyinstrument -r html"
help = "Profile cpu of task with pyinstrument"
