"""Parity tests for ossify.compartments against the original l2label output.

The reference artifacts in tests/data/l2label_reference/ were generated by
running the original meshparty-based l2label on the v1dd sample meshwork with
the bundled ``v1dd_ds15_us0_bd0`` model. These tests assert the ossify port
reproduces that output.
"""

import pathlib

import numpy as np
import pandas as pd
import pytest

pytest.importorskip("xgboost")
pytest.importorskip("sklearn")
pytest.importorskip("h5py")

import ossify
from ossify.compartments import (
    AxonLabel,
    CountFeature,
    DerivedFeature,
    MappedFeature,
    SkeletonVertexModel,
    get_models,
    load_model_config,
    make_skel_prop_df,
)

DATA = pathlib.Path(__file__).parent / "data"
REF = DATA / "l2label_reference"
MESHWORK = DATA / "v1dd_864691132533489754.h5"
MODEL = "v1dd_ds15_us0_bd0.json"

FEATURE_COLUMNS = [
    "area_um2",
    "vol_um3",
    "max_dt_um",
    "vol_to_area",
    "syn_in",
    "syn_out",
    "down_area_um2",
    "down_vol_um3",
    "down_max_dt_um",
    "down_vol_to_area",
    "down_syn_in",
    "down_syn_out",
]

pytestmark = pytest.mark.skipif(
    not MESHWORK.exists() or not REF.exists(),
    reason="v1dd sample meshwork and/or l2label reference artifacts not present",
)


@pytest.fixture(scope="module")
def cell():
    c, _ = ossify.import_legacy_meshwork(str(MESHWORK), as_pcg_skel=True)
    return c


@pytest.fixture(scope="module")
def labeler():
    return AxonLabel(MODEL)


def test_model_registry():
    assert MODEL in get_models()
    cfg = load_model_config(MODEL)
    assert cfg["downstream_hops"] == 15
    assert cfg["feature_columns"] == FEATURE_COLUMNS
    assert cfg["model_file"].exists()


def test_feature_extraction_parity(cell):
    df = make_skel_prop_df(
        cell, downstream_hops=15, upstream_hops=0, bidirectional_hops=0
    )
    ref = pd.read_pickle(REF / "v1dd_features.pkl")
    assert list(df.columns) == FEATURE_COLUMNS
    for col in FEATURE_COLUMNS:
        np.testing.assert_allclose(
            df[col].to_numpy(dtype=float),
            ref[col].to_numpy(dtype=float),
            rtol=1e-9,
            atol=1e-9,
            err_msg=f"feature column {col} differs from l2label reference",
        )


def test_synapse_counts_exact(cell):
    df = make_skel_prop_df(cell, downstream_hops=15)
    ref = pd.read_pickle(REF / "v1dd_features.pkl")
    np.testing.assert_array_equal(df["syn_in"].to_numpy(), ref["syn_in"].to_numpy())
    np.testing.assert_array_equal(df["syn_out"].to_numpy(), ref["syn_out"].to_numpy())


def test_vertex_prob_ratio_parity(cell, labeler):
    vpr = labeler.predict_vertex_prob_ratio(cell)
    ref = np.load(REF / "v1dd_vertex_prob_ratio.npy")
    np.testing.assert_allclose(vpr, ref, rtol=1e-9, atol=1e-9)


def test_segment_label_parity(cell, labeler):
    seg = labeler.predict_segment_label(cell)
    ref = np.load(REF / "v1dd_segment_label.npy")
    np.testing.assert_allclose(seg, ref, rtol=1e-9, atol=1e-9)


def test_axon_mask_parity(cell, labeler):
    mask = labeler.predict_axon_mask(cell)
    ref = np.load(REF / "v1dd_axon_mask_default.npy")
    np.testing.assert_array_equal(mask, ref)


def test_axon_mask_isolated_dendrite_flip_parity(cell, labeler):
    mask = labeler.predict_axon_mask(cell, evaluate_isolated_dendrites=True)
    ref = np.load(REF / "v1dd_axon_mask_flip.npy")
    np.testing.assert_array_equal(mask, ref)


def test_custom_feature_spec(cell):
    """A custom spec controls feature names, computation, and column order."""
    spec = [
        MappedFeature(
            "area", "area_nm2", map_agg="sum", scale=1.0, neighborhood_agg="sum"
        ),
        CountFeature("n_out", "pre_syn", neighborhood_agg="sum"),
        DerivedFeature(
            "syn_per_area",
            lambda df: df["n_out"] / (df["area"] + 1),
            inputs=["n_out", "area"],
        ),
    ]
    df = make_skel_prop_df(cell, downstream_hops=3, feature_spec=spec)
    # Columns are exactly the spec, base then neighborhood, in spec order.
    assert list(df.columns) == [
        "area",
        "n_out",
        "syn_per_area",
        "down_area",
        "down_n_out",
        "down_syn_per_area",
    ]
    # DerivedFeature is recomputed consistently from neighborhood columns.
    np.testing.assert_allclose(
        df["down_syn_per_area"].to_numpy(),
        (df["down_n_out"] / (df["down_area"] + 1)).to_numpy(),
    )
    # The custom "area" (no unit scale) is the default area_um2 times 1e6.
    ref = make_skel_prop_df(cell, downstream_hops=3)
    np.testing.assert_allclose(df["area"].to_numpy(), ref["area_um2"].to_numpy() * 1e6)


def test_predict_matches_default_axon_mask(cell, labeler):
    """The ABC template predict() equals the detailed mask with defaults."""
    np.testing.assert_array_equal(
        labeler.predict(cell), labeler.predict_axon_mask(cell)
    )


def test_custom_vertex_model_no_estimator(cell):
    """The SkeletonVertexModel template works for a non-XGBoost subclass."""

    class SynapseRichModel(SkeletonVertexModel):
        # A trivial heuristic model: "axon-like" where there are more outputs
        # than inputs in the downstream neighborhood. No estimator, no xgboost.
        def score(self, features):
            return (features["down_syn_out"] - features["down_syn_in"]).to_numpy()

        def assign(self, cell, scores):
            return scores > 0

    model = SynapseRichModel(downstream_hops=15)
    labels = model.predict(cell)
    assert labels.dtype == bool
    assert labels.shape[0] == cell.skeleton.n_vertices


def test_axon_mask_to_layer(cell, labeler):
    skel_mask = labeler.predict_axon_mask(cell)
    graph_mask = labeler.predict_axon_mask(cell, to_layer="graph")
    assert graph_mask.shape[0] == cell.graph.n_vertices
    assert graph_mask.dtype == bool
    # Mapping to another layer should preserve the rough axon fraction.
    assert abs(graph_mask.mean() - skel_mask.mean()) < 0.1


def test_predict_unaries(cell, labeler):
    from ossify.structured_prediction import TransitionSchema, decode_tree

    u = labeler.predict_unaries(cell)
    n = cell.skeleton.n_vertices
    assert u.shape == (n, 2)
    assert np.all(np.isfinite(u))
    # axon-preference (col1 - col0) is the natural-log odds; predict_vertex_prob_ratio
    # is the same thing in log2, so they agree up to ln(2).
    r = labeler.predict_vertex_prob_ratio(cell)
    np.testing.assert_allclose(u[:, 1] - u[:, 0], r * np.log(2), rtol=1e-6, atol=1e-9)
    # unaries + schema (built from the model's class order) decode without error.
    schema = TransitionSchema(
        classes=list(labeler.classes),
        transitions={("axon", "dendrite"): 10.0},
        root_classes=["dendrite"],
    )
    labels, edge_cost = decode_tree(cell.skeleton, u, schema)
    assert labels.shape == (n,)
    assert edge_cost.shape == (n,)


def test_computed_feature(cell):
    import ossify.compartments as cp

    n = cell.skeleton.n_vertices
    spec = [
        cp.ComputedFeature(
            "dtr", func=lambda c: c.skeleton.distance_to_root(as_positional=True)
        )
    ]
    df = cp.make_skel_prop_df_base(cell, feature_spec=spec)
    assert df.shape == (n, 1)
    np.testing.assert_allclose(
        df["dtr"].to_numpy(), cell.skeleton.distance_to_root(as_positional=True)
    )


def test_computed_feature_gets_neighborhood_aggregation(cell):
    import ossify.compartments as cp

    spec = [
        cp.ComputedFeature(
            "dtr",
            func=lambda c: c.skeleton.distance_to_root(as_positional=True),
            neighborhood_agg="mean",
        )
    ]
    df = cp.make_skel_prop_df(cell, downstream_hops=3, feature_spec=spec)
    assert "dtr" in df.columns and "down_dtr" in df.columns
