"""Machine-learning axon/dendrite compartment labeling for ossify cells.

This is a port of the `l2label` package onto ossify's `Cell`/`SkeletonLayer`
data structures. It extracts per-skeleton-vertex morphological + synaptic
features (optionally aggregated over graph neighborhoods), runs a trained
XGBoost classifier, smooths the per-vertex probabilities along the skeleton,
votes per segment, and restricts the dendrite to the root-connected component.

Requires the optional ``compartments`` extra (``pip install ossify[compartments]``)
for xgboost.

Notes for future generalization (kept intentionally close to l2label for now):
- The feature set and the binary axon/dendrite target are currently hard-coded
  to match the shipped models. Additional compartments (e.g. "primary axon",
  "apical dendrite") would require a multi-class target and richer features.
- The post-ML smoothing uses `algorithms.smooth_features` (global Laplacian
  heat-equation smoothing); the segment-vote + root-component heuristics that
  follow are candidates for replacement.
"""

import json
import pathlib
import warnings
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Callable, List, Literal, Optional, Sequence, Union

import numpy as np
import pandas as pd
from scipy import sparse

from .algorithms import (
    root_connected_mask,
    segment_aggregate,
    segregation_index,
    smooth_features,
)
from .base import Cell
from .structured_prediction import (
    TransitionSchema,
    absorb_small_compartments,
    decode_tree,
)

__all__ = [
    "make_skel_prop_df",
    "make_skel_prop_df_base",
    "SkeletonVertexModel",
    "ProbaVertexModel",
    "StructuredLabeler",
    "RootDecision",
    "root_policy",
    "AxonLabel",
    "get_models",
    "load_model_config",
    "MappedFeature",
    "CountFeature",
    "DerivedFeature",
    "ComputedFeature",
    "DEFAULT_FEATURE_SPEC",
    "DEFAULT_UNARY_CLIP",
]

# --- Model registry -------------------------------------------------------

MODEL_DIR = pathlib.Path(__file__).parent / "compartment_models"
DEFAULT_MODEL = "minnie65_ds15_us0_bd0.json"

#: Default symmetric clamp (in log-score / nat units) on per-vertex log-potentials.
#: A deliberately large rail: far above any realistic classifier log-odds and any
#: typical transition cost, so it never binds on real evidence and only tames
#: degenerate ``log(0) = -inf`` / float-limit values. See :class:`ProbaVertexModel`.
DEFAULT_UNARY_CLIP = 100.0


def get_models(dir: Optional[str] = None) -> list:
    """List the available bundled model configuration files."""
    import glob

    if dir is None:
        dir = MODEL_DIR
    return [pathlib.Path(f).name for f in glob.glob(f"{dir}/*.json")]


def load_model_config(
    model_name: Optional[str] = None,
    dir: Optional[str] = None,
) -> dict:
    """Load a model configuration file.

    Parameters
    ----------
    model_name : str, optional
        The filename of the model config to load. Defaults to the shipped
        minnie65 model when ``dir`` is also None.
    dir : str, optional
        Directory to load from. If None, the bundled model directory is used.
    """
    if dir is None:
        dir = MODEL_DIR
        if model_name is None:
            model_name = DEFAULT_MODEL
    if model_name is None:
        raise ValueError("model_name must be specified if dir is not provided")
    if not model_name.endswith(".json"):
        model_name += ".json"
    with open(pathlib.Path(dir) / model_name, "r") as f:
        model_config = json.load(f)
    model_config["model_file"] = pathlib.Path(dir) / model_config["model_file"]
    return model_config


# --- Feature specification -------------------------------------------------
#
# The feature set is described declaratively as an ordered list of feature
# definitions. Both the base per-vertex columns and their neighborhood-aggregated
# variants are generated by iterating this spec, so feature names, computation,
# and column order all come from the spec rather than being hard-coded. The
# default below reproduces the l2label feature set exactly; pass your own
# ``feature_spec`` to change layers, annotations, units, or add features.


@dataclass
class MappedFeature:
    """A feature mapped from another layer (e.g. graph volume properties).

    Parameters
    ----------
    name : str
        Output feature name (e.g. "area_um2").
    column : str
        Source column on ``source_layer`` (e.g. "area_nm2").
    source_layer : str
        Layer the column lives on. Default "graph".
    map_agg : str
        Aggregation when mapping source_layer -> skeleton (e.g. "sum", "max").
    scale : float
        Multiplicative unit conversion applied after mapping.
    neighborhood_agg : {"mean", "sum"}
        How the feature aggregates over a neighborhood. "mean" is the plain
        neighborhood mean; "sum" uses l2label's relative-hops normalization,
        which equals ``mean * (n_hops + 1)`` and preserves trained-model
        compatibility.
    """

    name: str
    column: str
    source_layer: str = "graph"
    map_agg: str = "sum"
    scale: float = 1.0
    neighborhood_agg: Literal["mean", "sum"] = "mean"


@dataclass
class CountFeature:
    """A feature counting nearby point annotations per skeleton vertex.

    Parameters
    ----------
    name : str
        Output feature name (e.g. "syn_in").
    annotation : str
        Annotation layer to count (e.g. "post_syn").
    distance_threshold : float
        Max distance for an annotation to count toward a vertex. Default 0
        (annotation's anchored vertex only).
    neighborhood_agg : {"mean", "sum"}
        See :class:`MappedFeature`.
    where : dict, str, or callable, optional
        Count only the subset of annotations matching this filter on their
        properties, e.g. ``{"target_type": "spine"}`` for a ``spine_in`` feature
        and ``{"target_type": "shaft"}`` for ``shaft_in``. A dict matches by
        equality / membership, a string is a pandas eval expression
        (``"target_type == 'spine'"``), or pass a callable on the annotation
        frame. ``None`` (default) counts all annotations.
    """

    name: str
    annotation: str
    distance_threshold: float = 0
    neighborhood_agg: Literal["mean", "sum"] = "sum"
    where: Union[dict, str, Callable, None] = None


@dataclass
class DerivedFeature:
    """A feature computed from other (earlier) feature columns.

    The ``func`` receives a DataFrame whose columns are the base feature names in
    ``inputs`` and returns the derived values. It is applied both to the base
    columns and, at each neighborhood prefix, to the prefixed input columns
    (renamed back to base names), so derived features aggregate consistently.

    Parameters
    ----------
    name : str
        Output feature name (e.g. "vol_to_area").
    func : Callable[[pd.DataFrame], pd.Series]
        Function over a DataFrame of the ``inputs`` columns.
    inputs : list of str
        Base feature names this depends on (must appear earlier in the spec).
    """

    name: str
    func: Callable[[pd.DataFrame], pd.Series]
    inputs: List[str] = field(default_factory=list)


@dataclass
class ComputedFeature:
    """A per-vertex feature produced by an arbitrary callable on the cell.

    The general escape hatch for features the built-in types don't cover (custom
    per-vertex statistics, externally-computed embeddings attached to vertices,
    etc.). ``func`` is called with the :class:`Cell` and must return a
    ``(n_vertices,)`` array in skeleton positional order. Like other primitive
    features it then flows through the neighborhood aggregation.

    Parameters
    ----------
    name : str
        Output feature name.
    func : Callable[[Cell], np.ndarray]
        Maps a cell to a per-vertex (positional) array.
    neighborhood_agg : {"mean", "sum"}
        See :class:`MappedFeature`.
    """

    name: str
    func: Callable[["Cell"], np.ndarray]
    neighborhood_agg: Literal["mean", "sum"] = "mean"


# Feature definitions are matched structurally; "primitive" features are those
# computed directly from the cell (mapped + counted + computed), as opposed to
# derived from earlier columns.
_PrimitiveFeature = (MappedFeature, CountFeature, ComputedFeature)
FeatureDef = Union[MappedFeature, CountFeature, ComputedFeature, DerivedFeature]


DEFAULT_FEATURE_SPEC: List[FeatureDef] = [
    MappedFeature(
        "area_um2", "area_nm2", map_agg="sum", scale=1e-6, neighborhood_agg="sum"
    ),
    MappedFeature(
        "vol_um3", "size_nm3", map_agg="sum", scale=1e-9, neighborhood_agg="sum"
    ),
    MappedFeature(
        "max_dt_um", "max_dt_nm", map_agg="max", scale=1e-3, neighborhood_agg="mean"
    ),
    DerivedFeature(
        "vol_to_area",
        lambda df: df["vol_um3"] / df["area_um2"],
        inputs=["vol_um3", "area_um2"],
    ),
    CountFeature("syn_in", "post_syn", neighborhood_agg="sum"),
    CountFeature("syn_out", "pre_syn", neighborhood_agg="sum"),
]


# --- Feature extraction ----------------------------------------------------


def make_skel_prop_df_base(
    cell: Cell,
    feature_spec: Optional[List[FeatureDef]] = None,
) -> pd.DataFrame:
    """Build the per-skeleton-vertex base feature dataframe from a feature spec.

    Parameters
    ----------
    cell : Cell
        Cell with a skeleton, source layer(s) carrying mapped features, and the
        annotation layers referenced by the spec.
    feature_spec : list of feature definitions, optional
        Ordered list of :class:`MappedFeature`, :class:`CountFeature`, and
        :class:`DerivedFeature`. Defaults to :data:`DEFAULT_FEATURE_SPEC` (the
        l2label feature set).

    Returns
    -------
    pd.DataFrame
        Indexed by skeleton vertex index, columns in spec order.
    """
    if feature_spec is None:
        feature_spec = DEFAULT_FEATURE_SPEC
    skel = cell.skeleton
    df = pd.DataFrame(index=skel.vertex_index)
    for f in feature_spec:
        if isinstance(f, MappedFeature):
            mapped = cell.layers[f.source_layer].map_features_to_layer(
                [f.column], "skeleton", agg={f.column: f.map_agg}
            )
            df[f.name] = (
                mapped[f.column].reindex(skel.vertex_index).to_numpy() * f.scale
            )
        elif isinstance(f, CountFeature):
            cnt = (
                skel.map_annotations_to_feature(
                    f.annotation,
                    distance_threshold=f.distance_threshold,
                    agg="count",
                    where=f.where,
                )
                .reindex(skel.vertex_index)
                .fillna(0)
                .astype(int)
            )
            df[f.name] = cnt.to_numpy()
        elif isinstance(f, ComputedFeature):
            df[f.name] = np.asarray(f.func(cell), dtype=float)
        elif isinstance(f, DerivedFeature):
            df[f.name] = np.asarray(f.func(df[f.inputs]))
        else:
            raise TypeError(f"Unknown feature definition type: {type(f)}")
    return df


def _add_neighborhood_features(
    cell: Cell,
    df: pd.DataFrame,
    feature_spec: List[FeatureDef],
    prefix: str,
    radius: int,
    scale_hops: int,
    direction: Literal["downstream", "upstream", "undirected"],
) -> pd.DataFrame:
    """Aggregate spec features over each vertex's k-hop neighborhood, in place.

    Columns are emitted in spec order as ``{prefix}_{name}``.
    """
    skel = cell.skeleton
    primitive_names = [f.name for f in feature_spec if isinstance(f, _PrimitiveFeature)]
    means = skel.aggregate_features(
        df[primitive_names],
        radius=radius,
        metric="hops",
        direction=direction,
        agg="mean",
    )
    factor = scale_hops + 1
    for f in feature_spec:
        out = f"{prefix}_{f.name}"
        if isinstance(f, _PrimitiveFeature):
            vals = means[f.name].to_numpy()
            if f.neighborhood_agg == "sum":
                vals = vals * factor
            df[out] = vals
        elif isinstance(f, DerivedFeature):
            sub = df[[f"{prefix}_{c}" for c in f.inputs]].copy()
            sub.columns = f.inputs
            df[out] = np.asarray(f.func(sub))
    return df


def make_skel_prop_df(
    cell: Cell,
    downstream_hops: int = 5,
    upstream_hops: int = 0,
    bidirectional_hops: int = 0,
    label: Optional[str] = None,
    *,
    feature_spec: Optional[List[FeatureDef]] = None,
) -> pd.DataFrame:
    """Generate the per-skeleton-vertex feature dataframe with neighborhood aggregation.

    Parameters
    ----------
    cell : Cell
        Cell with skeleton, mapped source features, and the annotation layers
        referenced by the spec.
    downstream_hops : int
        Hops to aggregate downstream (toward tips). 0 disables.
    upstream_hops : int
        Hops to aggregate upstream (toward root). 0 disables.
    bidirectional_hops : int
        Hops to aggregate in any direction. 0 disables.
    label : str, optional
        If given, the name of a boolean skeleton feature to copy into an
        "is_axon" column (used for training).
    feature_spec : list of feature definitions, optional
        See :func:`make_skel_prop_df_base`. Defaults to :data:`DEFAULT_FEATURE_SPEC`.

    Returns
    -------
    pd.DataFrame
        Indexed by skeleton vertex index.
    """
    if feature_spec is None:
        feature_spec = DEFAULT_FEATURE_SPEC
    df = make_skel_prop_df_base(cell, feature_spec=feature_spec)
    if downstream_hops > 0:
        _add_neighborhood_features(
            cell,
            df,
            feature_spec,
            "down",
            downstream_hops,
            downstream_hops,
            "downstream",
        )
    if upstream_hops > 0:
        _add_neighborhood_features(
            cell, df, feature_spec, "up", upstream_hops, upstream_hops, "upstream"
        )
    if bidirectional_hops > 0:
        # Matches l2label: neighborhood radius is bidirectional_hops, but the
        # normalization divisor uses 2 * bidirectional_hops.
        _add_neighborhood_features(
            cell,
            df,
            feature_spec,
            "bidir",
            bidirectional_hops,
            2 * bidirectional_hops,
            "undirected",
        )
    if label is not None:
        df["is_axon"] = cell.skeleton.get_feature(label)
    return df


# --- Generic vertex-labeling template --------------------------------------


class SkeletonVertexModel(ABC):
    """Abstract template for predicting per-vertex labels on a Cell's skeleton.

    The shared flow is ``extract_features -> score -> smooth -> assign``,
    expressed by :meth:`predict`. Subclasses provide:

    - :meth:`score` (required): per-vertex prediction from the feature dataframe
      (e.g. a model's class probabilities, or a heuristic statistic).
    - :meth:`assign` (optional): turn the (smoothed) scores into final labels.
      The default takes the per-vertex argmax over score columns -- the
      structure-free baseline. Override for a domain-specific label step.
    - :meth:`smooth` (optional): graph-aware smoothing of the scores; the default
      is the identity. Override e.g. with :func:`ossify.algorithms.smooth_features`.

    A model is used in one of two ways. On its own it is a per-vertex labeler
    (``predict``). As an **encoder** it produces unaries (``predict_unaries``)
    for a :class:`StructuredLabeler`, which applies the
    :class:`~ossify.structured_prediction.TransitionSchema` priors and an exact
    tree decode -- the ``encode -> decode -> clean`` pipeline. The same model
    fills either role; :meth:`assign` matters only for the standalone path.

    Feature extraction is shared and driven by ``feature_spec`` (see
    :func:`make_skel_prop_df`); subclasses with different feature needs just pass
    a different spec. This keeps model-specific concerns (the estimator, the
    label semantics) in subclasses while the orchestration and the
    graph-aggregation feature machinery stay general.
    """

    def __init__(
        self,
        downstream_hops: int = 0,
        upstream_hops: int = 0,
        bidirectional_hops: int = 0,
        feature_spec: Optional[List[FeatureDef]] = None,
    ):
        self._downstream_hops = downstream_hops
        self._upstream_hops = upstream_hops
        self._bidirectional_hops = bidirectional_hops
        self._feature_spec = feature_spec

    def extract_features(
        self, cell: Cell, label: Optional[str] = None, **kwargs
    ) -> pd.DataFrame:
        """Build the per-vertex feature dataframe for the cell's skeleton."""
        kwargs.setdefault("feature_spec", self._feature_spec)
        return make_skel_prop_df(
            cell,
            downstream_hops=self._downstream_hops,
            upstream_hops=self._upstream_hops,
            bidirectional_hops=self._bidirectional_hops,
            label=label,
            **kwargs,
        )

    @abstractmethod
    def score(self, features: pd.DataFrame) -> np.ndarray:
        """Per-vertex raw scores from the feature dataframe (positional order)."""

    def smooth(self, cell: Cell, scores: np.ndarray) -> np.ndarray:
        """Optionally smooth scores along the skeleton graph. Default: identity."""
        return scores

    def assign(self, cell: Cell, scores: np.ndarray) -> np.ndarray:
        """Turn (smoothed) per-vertex scores into final labels.

        Default: per-vertex argmax over the score columns -- the structure-free
        baseline that ignores graph topology. Override for a domain-specific
        label step, or feed :meth:`predict_unaries` to a :class:`StructuredLabeler`
        for a topology-aware decode instead.
        """
        return np.asarray(scores).argmax(axis=1)

    def predict(self, cell: Cell) -> np.ndarray:
        """Run the full extract -> score -> smooth -> assign flow."""
        features = self.extract_features(cell)
        scores = self.score(features)
        scores = self.smooth(cell, scores)
        return self.assign(cell, scores)

    def to_unaries(self, scores: np.ndarray) -> np.ndarray:
        """Convert per-vertex scores to additive log-potentials (unaries).

        Default assumes :meth:`score` returns class probabilities and takes their
        log. Override if ``score`` already produces log-space scores or needs a
        different transform.
        """
        return np.log(np.clip(np.asarray(scores, dtype=float), 1e-9, None))

    def predict_unaries(self, cell: Cell, smooth: bool = True) -> np.ndarray:
        """Per-vertex log-potentials for the structured-prediction decoder.

        Runs ``extract -> score (-> smooth) -> to_unaries`` and returns an
        ``(n_vertices, K)`` array of additive log-scores, columns in the same
        class order as :meth:`score`. Feed these to
        :func:`ossify.structured_prediction.decode_tree` together with a
        ``TransitionSchema`` whose classes are listed in that same order.

        Parameters
        ----------
        cell : Cell
        smooth : bool
            Apply the model's :meth:`smooth` hook before converting to unaries
            (default True). Pass False to let the decoder's transition costs do
            all the graph coupling.
        """
        scores = self.score(self.extract_features(cell))
        if smooth:
            scores = self.smooth(cell, scores)
        return self.to_unaries(scores)


# --- Axon/dendrite classifier ----------------------------------------------


class AxonLabel(SkeletonVertexModel):
    """XGBoost axon/dendrite compartment classifier on ossify cells.

    .. deprecated::
        Use a :class:`ProbaVertexModel` encoder fed to a :class:`StructuredLabeler`
        (the ``encode -> decode -> clean`` pipeline). The bundled XGBoost models
        load via :meth:`ProbaVertexModel.from_config`. The structured decode replaces this
        class's segment-vote/root-component heuristic with an exact tree-MAP under
        declared :class:`~ossify.structured_prediction.TransitionSchema` priors,
        and generalizes past the hard-coded binary axon/dendrite target.

    A concrete :class:`SkeletonVertexModel`: :meth:`score` is the XGBoost class
    probability, :meth:`smooth` is Laplacian smoothing along the skeleton, and
    :meth:`assign` applies the segment-vote + root-component (+ optional
    isolated-dendrite) labeling. :meth:`predict_axon_mask` is the full-featured
    entry point; :meth:`predict` returns the default mask.
    """

    #: Class order of :meth:`score` / :meth:`predict_unaries` columns. The
    #: XGBoost model is trained on ``is_axon`` (False, True), so column 0 is the
    #: non-axon class (dendrite/soma) and column 1 is axon. Build a
    #: ``TransitionSchema`` with ``classes=AxonLabel.classes`` to keep the
    #: decoder's columns aligned with the unaries.
    classes = ("dendrite", "axon")

    def __init__(
        self,
        config: Optional[Union[dict, str]] = None,
        downstream_hops: Optional[int] = None,
        upstream_hops: Optional[int] = None,
        bidirectional_hops: Optional[int] = None,
        spread_alpha: Optional[float] = None,
        model=None,
        feature_columns: Optional[list] = None,
        feature_spec: Optional[List[FeatureDef]] = None,
    ):
        warnings.warn(
            "AxonLabel is deprecated; build a ProbaVertexModel encoder and feed it "
            "to a StructuredLabeler (see ProbaVertexModel.from_config for the "
            "bundled XGBoost models). AxonLabel's segment-vote/root-component "
            "heuristic is superseded by the structured tree decode.",
            DeprecationWarning,
            stacklevel=2,
        )
        if config is not None or (
            downstream_hops is None
            and upstream_hops is None
            and bidirectional_hops is None
            and model is None
            and spread_alpha is None
        ):
            if not isinstance(config, dict):
                config = load_model_config(config, dir=None)
            downstream_hops = config.get("downstream_hops")
            upstream_hops = config.get("upstream_hops")
            bidirectional_hops = config.get("bidirectional_hops")
            self._spread_alpha = config.get("spread_alpha")
            self._feature_columns = config.get("feature_columns")
            self._load_model(config.get("model_file"))
        else:
            if (
                downstream_hops is None
                or upstream_hops is None
                or bidirectional_hops is None
                or model is None
                or spread_alpha is None
            ):
                raise ValueError(
                    "Must provide either a config or all of downstream_hops, "
                    "upstream_hops, bidirectional_hops, spread_alpha and model."
                )
            self._spread_alpha = spread_alpha
            self._model = model
            self._feature_columns = feature_columns
        super().__init__(
            downstream_hops=downstream_hops,
            upstream_hops=upstream_hops,
            bidirectional_hops=bidirectional_hops,
            feature_spec=feature_spec,
        )

    @property
    def parameters(self) -> dict:
        "Feature extraction parameters."
        return {
            "downstream_hops": self._downstream_hops,
            "upstream_hops": self._upstream_hops,
            "bidirectional_hops": self._bidirectional_hops,
            "spread_alpha": self._spread_alpha,
            "feature_columns": self._feature_columns,
        }

    @property
    def model_parameters(self) -> dict:
        "XGBoost model parameters."
        return self._model.get_params()

    def _load_model(self, filepath) -> None:
        import xgboost

        self._model = xgboost.XGBClassifier()
        self._model._estimator_type = "classifier"
        self._model.load_model(filepath)

    # --- SkeletonVertexModel hooks -----------------------------------------

    def score(self, features: pd.DataFrame) -> np.ndarray:
        """Per-vertex XGBoost class probabilities (n_vertices x 2)."""
        return self._model.predict_proba(features[self._feature_columns].values)

    def smooth(self, cell: Cell, scores: np.ndarray) -> np.ndarray:
        """Laplacian smoothing of the class probabilities along the skeleton."""
        return smooth_features(
            cell.skeleton, scores.astype(float), alpha=self._spread_alpha
        )

    def assign(self, cell: Cell, scores: np.ndarray) -> np.ndarray:
        """Default axon mask from smoothed probabilities (no extra options)."""
        vertex_prob_ratio = np.log2(scores[:, 1] / scores[:, 0])
        seg_label = segment_aggregate(cell, vertex_prob_ratio, agg="mean")
        return self._axon_mask_from_segment_label(cell, seg_label)

    # --- Domain API --------------------------------------------------------

    def predict_vertex_prob_ratio(
        self,
        cell: Cell,
        root_is_soma: bool = False,
        **kwargs,
    ) -> np.ndarray:
        """Per-vertex log2 ratio of axon to non-axon probability (smoothed).

        Higher values are axon-like. Indexed by skeleton positional order.
        """
        features = self.extract_features(cell, **kwargs)
        is_axon_prob = self.score(features)
        if root_is_soma:
            root = cell.skeleton.root_positional
            is_axon_prob[root, 0] = 0.99999999
            is_axon_prob[root, 1] = 1 - is_axon_prob[root, 0]
        label = self.smooth(cell, is_axon_prob)
        return np.log2(label[:, 1] / label[:, 0])

    def predict_segment_label(
        self,
        cell: Cell,
        vertex_prob_ratio: Optional[np.ndarray] = None,
        root_is_soma: bool = False,
        **kwargs,
    ) -> np.ndarray:
        """Per-vertex axon log-ratio, averaged within each skeleton segment."""
        if vertex_prob_ratio is None:
            vertex_prob_ratio = self.predict_vertex_prob_ratio(
                cell, root_is_soma=root_is_soma, **kwargs
            )
        return segment_aggregate(cell, vertex_prob_ratio, agg="mean")

    def _axon_mask_from_segment_label(
        self,
        cell: Cell,
        seg_label: np.ndarray,
        root_compartment: bool = True,
        threshold: float = 0,
        root_is_soma: bool = False,
        evaluate_isolated_dendrites: bool = False,
    ) -> np.ndarray:
        """Build the axon mask from a per-vertex segment label."""
        skel = cell.skeleton
        is_axon_base = seg_label > threshold
        if root_compartment:
            if evaluate_isolated_dendrites:
                is_axon_base = self._flip_isolated_dendrite_components(
                    cell, root_is_soma=root_is_soma, is_axon_seg=seg_label
                )
            in_root_comp = root_connected_mask(
                cell, np.flatnonzero(is_axon_base), as_positional=True
            )
        else:
            in_root_comp = np.full(skel.n_vertices, True)
        return ~np.logical_and(~is_axon_base, in_root_comp)

    def predict_axon_mask(
        self,
        cell: Cell,
        root_compartment: bool = True,
        threshold: float = 0,
        root_is_soma: bool = False,
        is_axon_seg: Optional[np.ndarray] = None,
        evaluate_isolated_dendrites: bool = False,
        to_layer: Optional[str] = None,
        **kwargs,
    ) -> np.ndarray:
        """Predict a boolean axon mask over skeleton vertices.

        Parameters
        ----------
        cell : Cell
        root_compartment : bool
            If True, only the dendrite component connected to the root stays
            dendrite; disconnected dendrite-labeled islands become axon.
        threshold : float
            Segment log-ratio threshold above which a segment is axon.
        root_is_soma : bool
            Force the root probability toward dendrite.
        is_axon_seg : np.ndarray, optional
            Precomputed per-vertex segment label.
        evaluate_isolated_dendrites : bool
            If True, flip isolated dendrite components whose path-to-root is
            dendrite-like and which improve the segregation index.
        to_layer : str, optional
            If given, return the mask mapped to this layer (e.g. "graph"/"mesh").

        Returns
        -------
        np.ndarray
            Boolean axon mask over skeleton vertices (or the target layer).
        """
        if is_axon_seg is None:
            seg_label = self.predict_segment_label(
                cell, root_is_soma=root_is_soma, **kwargs
            )
        else:
            seg_label = is_axon_seg
        is_axon = self._axon_mask_from_segment_label(
            cell,
            seg_label,
            root_compartment=root_compartment,
            threshold=threshold,
            root_is_soma=root_is_soma,
            evaluate_isolated_dendrites=evaluate_isolated_dendrites,
        )
        if to_layer is not None:
            return cell.skeleton.map_mask_to_layer(to_layer, is_axon)
        return is_axon

    # --- isolated dendrite flipping (faithful l2label port) ----------------

    def _find_dendrite_components(self, cell: Cell, segment_label: np.ndarray) -> tuple:
        skel = cell.skeleton
        nonroot_inds = np.setdiff1d(np.arange(skel.n_vertices), [skel.root_positional])
        child_category = np.sign(segment_label[nonroot_inds])
        parent_category = np.sign(segment_label[skel.parent_node_array[nonroot_inds]])
        cut_points = np.flatnonzero(child_category != parent_category)

        G = skel.cut_graph(
            cut_points, directed=False, euclidean_weight=False, as_positional=True
        )
        _, comp_labels = sparse.csgraph.connected_components(G, directed=False)

        dtr = skel.distance_to_root(as_positional=True)
        comps = []
        comp_is_dendrite = []
        for lbl in np.unique(comp_labels):
            comps.append(np.flatnonzero(comp_labels == lbl))
            comp_is_dendrite.append(segment_label[comps[-1][0]] < 0)
        comp_is_dendrite = np.array(comp_is_dendrite)
        dend_comps = [
            c
            for c, is_dend in zip(comps, comp_is_dendrite)
            if is_dend and skel.root_positional not in c
        ]
        dend_comp_dtr = np.array([np.min(dtr[c]) for c in dend_comps])
        isolated_comps = np.argsort(dend_comp_dtr)[::-1]
        return dend_comps, isolated_comps

    def _path_to_root(self, cell: Cell, start: int) -> np.ndarray:
        """Positional path from a vertex up to the root."""
        pna = cell.skeleton.parent_node_array
        path = [int(start)]
        current = int(start)
        while pna[current] != -1:
            current = int(pna[current])
            path.append(current)
        return np.array(path, dtype=int)

    def _evaluate_isolated_dendrite_components(
        self,
        cell,
        is_axon_prob,
        is_axon_seg,
        is_axon,
        dend_comps,
        isolated_comps,
        pre_syn,
        post_syn,
    ):
        skel = cell.skeleton
        pre_sk = cell.annotations[pre_syn].map_index_to_layer(
            "skeleton", as_positional=True
        )
        post_sk = cell.annotations[post_syn].map_index_to_layer(
            "skeleton", as_positional=True
        )
        costs = []
        gains = []
        for cind in isolated_comps:
            c = dend_comps[cind]
            ptr = self._path_to_root(cell, c[0])
            costs.append(is_axon_prob[ptr].mean() * len(ptr))

            is_axon_seg_option = is_axon_seg.copy()
            is_axon_seg_option[ptr] = -1
            is_axon_option = self.predict_axon_mask(
                cell, root_compartment=True, is_axon_seg=is_axon_seg_option
            )

            def _seg(mask):
                return segregation_index(
                    int(np.sum(mask[pre_sk])),
                    int(np.sum(mask[post_sk])),
                    int(np.sum(~mask[pre_sk])),
                    int(np.sum(~mask[post_sk])),
                )

            gains.append(_seg(is_axon_option) - _seg(is_axon))
        return costs, gains

    def _flip_isolated_dendrite_components(
        self,
        cell: Cell,
        root_is_soma: bool = False,
        is_axon_prob: Optional[np.ndarray] = None,
        is_axon_seg: Optional[np.ndarray] = None,
        pre_syn: str = "pre_syn",
        post_syn: str = "post_syn",
    ) -> np.ndarray:
        if is_axon_prob is None:
            is_axon_prob = self.predict_vertex_prob_ratio(cell)
        if is_axon_seg is None:
            is_axon_seg = self.predict_segment_label(cell)
        is_axon = self.predict_axon_mask(
            cell,
            root_compartment=True,
            root_is_soma=root_is_soma,
            is_axon_seg=is_axon_seg,
        )
        dend_comps, isolated_comps = self._find_dendrite_components(cell, is_axon_seg)
        costs, gains = self._evaluate_isolated_dendrite_components(
            cell,
            is_axon_prob,
            is_axon_seg,
            is_axon,
            dend_comps,
            isolated_comps,
            pre_syn,
            post_syn,
        )
        for c, g, cind in zip(costs, gains, isolated_comps):
            if c < 0 and g > 0:
                ptr = self._path_to_root(cell, dend_comps[cind][0])
                is_axon_seg[ptr] = -1
        return self.predict_axon_mask(
            cell,
            root_compartment=True,
            root_is_soma=root_is_soma,
            is_axon_seg=is_axon_seg,
        )


# --- Probability encoder ----------------------------------------------------


def _load_xgboost_classifier(filepath):
    """Load a saved XGBoost classifier from ``filepath`` (booster JSON/UBJ)."""
    import xgboost

    model = xgboost.XGBClassifier()
    model._estimator_type = "classifier"
    model.load_model(filepath)
    return model


class ProbaVertexModel(SkeletonVertexModel):
    """Per-vertex probability encoder wrapping any ``predict_proba`` estimator.

    The **encode** stage of the ``encode -> decode -> clean`` pipeline. It owns
    the feature extraction, the fitted classifier, and the optional probability
    smoothing; its :meth:`predict_unaries` output feeds a :class:`StructuredLabeler`
    for the topology-aware decode. Used on its own, :meth:`predict` returns the
    structure-free per-vertex argmax.

    The classifier is **any fitted estimator exposing ``predict_proba``**
    (XGBoost, scikit-learn ``RandomForestClassifier``, a future GNN wrapper, ...);
    nothing here is XGBoost-specific. Its ``classes_`` (when present) define the
    probability column order, which a :class:`StructuredLabeler` validates against
    its schema.

    Parameters
    ----------
    estimator : object
        Fitted classifier with ``predict_proba(X) -> (n, K)``.
    feature_columns : list of str
        Columns of the extracted feature frame to feed the estimator, in the
        order it was trained on.
    downstream_hops, upstream_hops, bidirectional_hops : int
        Neighborhood-aggregation radii for feature extraction (must match how
        the estimator was trained).
    smooth_alpha : float, optional
        If given, Laplacian-smooth the probabilities along the skeleton with this
        alpha. Default ``None`` leaves graph coupling to the decoder's transition
        costs.
    unary_clip : float
        Numerical guard on the per-vertex log-potentials: :meth:`to_unaries`
        clamps each class's unary to ``[-unary_clip, +unary_clip]``, keeping a
        zero probability from becoming ``log(0) = -inf`` (which would poison the
        decode's sums) and bounding magnitudes that float precision makes
        meaningless. It is expressed in the same log-score (nat) units as a
        :class:`~ossify.structured_prediction.TransitionSchema`'s transition
        costs. The default :data:`DEFAULT_UNARY_CLIP` is a deliberately large rail
        -- **comfortably above any transition cost** -- so it never binds on real
        evidence and does not change the labeling; it only tames degenerate
        ``0``/``1`` probabilities. Set *below* a transition cost it stops being a
        pure guard and becomes a confidence cap that can change results (it then
        caps the log-odds between any two classes at ``unary_clip`` -- equivalent
        to flooring probabilities at ``exp(-unary_clip)``); that regime is opt-in.
    feature_spec : list of feature definitions, optional
        See :func:`make_skel_prop_df`. Defaults to :data:`DEFAULT_FEATURE_SPEC`.
    """

    def __init__(
        self,
        estimator,
        feature_columns: List[str],
        *,
        downstream_hops: int = 0,
        upstream_hops: int = 0,
        bidirectional_hops: int = 0,
        smooth_alpha: Optional[float] = None,
        unary_clip: float = DEFAULT_UNARY_CLIP,
        feature_spec: Optional[List[FeatureDef]] = None,
    ):
        if unary_clip is None or unary_clip <= 0.0:
            raise ValueError(
                f"unary_clip must be a positive number; got {unary_clip!r}."
            )
        self._estimator = estimator
        self._feature_columns = list(feature_columns)
        self._smooth_alpha = smooth_alpha
        self._unary_clip = float(unary_clip)
        super().__init__(
            downstream_hops=downstream_hops,
            upstream_hops=upstream_hops,
            bidirectional_hops=bidirectional_hops,
            feature_spec=feature_spec,
        )

    @classmethod
    def from_config(
        cls,
        config: Optional[Union[dict, str]] = None,
        *,
        smooth_alpha: Optional[float] = None,
        unary_clip: Optional[float] = None,
        feature_spec: Optional[List[FeatureDef]] = None,
    ) -> "ProbaVertexModel":
        """Build from a bundled XGBoost model config.

        Loads the estimator, feature columns, and hop settings from a shipped
        model config (see :func:`load_model_config`). ``smooth_alpha`` defaults to
        the config's ``spread_alpha``; ``unary_clip`` to the config's ``unary_clip``
        key, falling back to :data:`DEFAULT_UNARY_CLIP`.
        """
        if not isinstance(config, dict):
            config = load_model_config(config, dir=None)
        if smooth_alpha is None:
            smooth_alpha = config.get("spread_alpha")
        if unary_clip is None:
            unary_clip = config.get("unary_clip", DEFAULT_UNARY_CLIP)
        return cls(
            _load_xgboost_classifier(config["model_file"]),
            config["feature_columns"],
            downstream_hops=config.get("downstream_hops", 0),
            upstream_hops=config.get("upstream_hops", 0),
            bidirectional_hops=config.get("bidirectional_hops", 0),
            smooth_alpha=smooth_alpha,
            unary_clip=unary_clip,
            feature_spec=feature_spec,
        )

    @property
    def estimator(self):
        return self._estimator

    @property
    def feature_columns(self) -> list:
        return list(self._feature_columns)

    @property
    def classes_(self):
        """The estimator's class order, if it exposes ``classes_`` (else None)."""
        c = getattr(self._estimator, "classes_", None)
        return None if c is None else list(c)

    # --- SkeletonVertexModel hooks -----------------------------------------

    def score(self, features: pd.DataFrame) -> np.ndarray:
        """Per-vertex class probabilities ``(n_vertices, K)`` from the estimator."""
        return self._estimator.predict_proba(features[self._feature_columns].values)

    def smooth(self, cell: Cell, scores: np.ndarray) -> np.ndarray:
        """Optional Laplacian smoothing of probabilities; identity if no alpha."""
        if self._smooth_alpha is None:
            return scores
        return smooth_features(
            cell.skeleton, scores.astype(float), alpha=self._smooth_alpha
        )

    def to_unaries(self, scores: np.ndarray) -> np.ndarray:
        """Log-potentials from probabilities, clamped to ``+/- unary_clip``.

        Primarily a numerical guard: ``log(p)`` sends a zero probability to
        ``-inf``, which poisons the decode's sums, and float limits make very
        large magnitudes meaningless anyway. ``unary_clip`` bounds the result to a
        finite range; at the default :data:`DEFAULT_UNARY_CLIP` it never binds on
        real evidence and so does not change the labeling. See ``unary_clip`` in
        the class docstring.
        """
        floor = float(np.exp(-self._unary_clip))
        clipped = np.clip(np.asarray(scores, dtype=float), floor, None)
        return np.clip(np.log(clipped), -self._unary_clip, self._unary_clip)


# --- Structured compartment labeler -----------------------------------------


class StructuredLabeler:
    """Compose an encoder + transition priors into a tree-decoded labeler.

    The **decode -> clean** seat of the ``encode -> decode -> clean`` pipeline,
    and the principled successor to :class:`AxonLabel`'s segment-vote/root-component
    heuristic. It pulls per-vertex unaries from any :class:`SkeletonVertexModel`
    encoder (:meth:`~SkeletonVertexModel.predict_unaries`), applies the
    :class:`~ossify.structured_prediction.TransitionSchema` priors via an exact
    tree-MAP :func:`~ossify.structured_prediction.decode_tree`, and optionally
    runs :func:`~ossify.structured_prediction.absorb_small_compartments` to clean
    up short, noise-driven label flips.

    Keeping the encoder a separate object is the point: ossify owns the priors and
    the exact inference, the encoder owns features->probabilities, and either side
    can be swapped (a tabular classifier today, a GNN later) without touching the
    other. The decode/schema/absorb stack is fully K-class, so multi-compartment
    targets (soma / basal / apical / axon) need only a richer estimator and schema.

    Parameters
    ----------
    encoder : SkeletonVertexModel
        Produces ``(n_vertices, K)`` unaries via ``predict_unaries`` -- typically
        a :class:`ProbaVertexModel`, but any subclass works.
    schema : TransitionSchema
        Declares the class names, transition priors, and ``default_cost``. There
        is intentionally no default: a new estimator must declare its own priors.
        ``schema.classes`` must match the encoder's class order (validated when
        the encoder exposes ``classes_``).
    absorb_min_size : int, optional
        Absorb decoded compartments with this many vertices or fewer.
    absorb_min_weight : float, optional
        Absorb decoded compartments whose cable length (``half_edge_length``) is
        this or less.
    """

    def __init__(
        self,
        encoder: SkeletonVertexModel,
        schema: TransitionSchema,
        *,
        absorb_min_size: Optional[int] = None,
        absorb_min_weight: Optional[float] = None,
    ):
        self._encoder = encoder
        self._schema = schema
        self._absorb_min_size = absorb_min_size
        self._absorb_min_weight = absorb_min_weight
        self._validate_classes()

    def _validate_classes(self) -> None:
        """Check schema.classes lines up with the encoder's class order.

        When the encoder exposes ``classes_`` (e.g. a :class:`ProbaVertexModel`
        over a fitted estimator), the column count and order are checked: a
        ``range(K)`` / ``[False, True]`` placeholder just supplies the count and
        the schema names the classes; meaningful labels must match in order. An
        encoder without ``classes_`` is validated against the unary width at
        decode time.
        """
        est_classes = getattr(self._encoder, "classes_", None)
        if est_classes is None:
            return  # validated against unary width in _decode()
        est_classes = list(est_classes)
        K = len(est_classes)
        if len(self._schema.classes) != K:
            raise ValueError(
                f"schema has {len(self._schema.classes)} classes but the "
                f"encoder predicts {K}."
            )
        if est_classes != list(range(K)) and est_classes != list(self._schema.classes):
            raise ValueError(
                f"encoder.classes_={est_classes} must match schema.classes="
                f"{list(self._schema.classes)} in order; these define the "
                "probability/unary column order."
            )

    @property
    def encoder(self) -> SkeletonVertexModel:
        return self._encoder

    @property
    def classes(self) -> tuple:
        """Class labels, in unary/probability column order (from the schema)."""
        return tuple(self._schema.classes)

    @property
    def schema(self) -> TransitionSchema:
        return self._schema

    def predict_unaries(self, cell: Cell) -> np.ndarray:
        """The encoder's ``(n_vertices, K)`` log-potentials for this cell."""
        return self._encoder.predict_unaries(cell)

    def _decode(self, cell: Cell):
        """Decode the encoder's unaries to labels + per-edge violation costs."""
        unaries = self._encoder.predict_unaries(cell)
        if unaries.shape[1] != len(self._schema.classes):
            raise ValueError(
                f"encoder produced {unaries.shape[1]} unary columns but schema "
                f"has {len(self._schema.classes)} classes."
            )
        labels, edge_cost = decode_tree(
            cell.skeleton, unaries, self._schema, return_labels_as="index"
        )
        if self._absorb_min_size is not None or self._absorb_min_weight is not None:
            labels = absorb_small_compartments(
                cell.skeleton,
                labels,
                min_size=self._absorb_min_size,
                min_weight=self._absorb_min_weight,
            )
        return labels, edge_cost

    def _as_labels(self, indices: np.ndarray, return_labels_as: str) -> np.ndarray:
        if return_labels_as == "index":
            return indices
        if return_labels_as == "label":
            return np.array(self._schema.classes, dtype=object)[indices]
        raise ValueError("return_labels_as must be 'index' or 'label'.")

    def predict(self, cell: Cell, return_labels_as: str = "label") -> np.ndarray:
        """Per-vertex compartment labels via decode (+absorb).

        ``return_labels_as`` is ``"label"`` (schema class labels, default) or
        ``"index"`` (class indices).
        """
        labels, _ = self._decode(cell)
        return self._as_labels(labels, return_labels_as)

    def predict_with_violations(self, cell: Cell, return_labels_as: str = "label"):
        """Labels plus the per-edge transition cost paid to the parent.

        Returns ``(labels, edge_cost)``; nonzero ``edge_cost`` entries are the
        decoder's transition violations (a morphology QC signal). Costs are from
        the decode, before any small-compartment absorption.
        """
        labels, edge_cost = self._decode(cell)
        return self._as_labels(labels, return_labels_as), edge_cost


# --- Rooting policy ---------------------------------------------------------
#
# The structured decode's directional priors are *root-relative*: "axon does not
# revert to dendrite as you move away from the root" only means what we want if
# the root sits at the soma/proximal end. Some cells in large datasets get an
# incorrect root, which silently inverts the prior. This policy re-derives the
# root from a-priori information (a nucleus) and, failing that, from the encoder's
# own probabilities -- but only re-roots onto a *convincing span* of the anchor
# class, never a single noisy argmax vertex. It is a pure decision (no mutation);
# inspect the returned RootDecision as a dry run, then call .apply to commit.


def _tree_mask_components(
    parent_array: np.ndarray, root: int, mask: np.ndarray
) -> np.ndarray:
    """Label maximal connected runs of ``mask``-True nodes on the rooted tree.

    Returns a ``(n,)`` array of component ids (the top-most node of each run);
    ``mask``-False nodes get ``-1``. Mirrors the compartment-id pass in
    :func:`~ossify.structured_prediction.tree_absorb_small_compartments`, but
    over a boolean membership mask rather than a label array.
    """
    n = parent_array.shape[0]
    children: List[List[int]] = [[] for _ in range(n)]
    for v in range(n):
        p = parent_array[v]
        if v != root and p >= 0:
            children[p].append(v)
    order: List[int] = []
    stack = [root]
    while stack:
        v = stack.pop()
        order.append(v)
        stack.extend(children[v])
    comp = np.full(n, -1, dtype=int)
    for v in order:
        if not mask[v]:
            continue
        p = parent_array[v]
        if v == root or p < 0 or not mask[p]:
            comp[v] = v
        else:
            comp[v] = comp[p]
    return comp


def _oncomponent_window_sum(
    parent_array: np.ndarray,
    root: int,
    member_mask: np.ndarray,
    values: np.ndarray,
    window_hops: int,
) -> np.ndarray:
    """Sum ``values`` over each vertex's ``<=window_hops`` neighborhood, confined
    to its connected component of ``member_mask`` vertices.

    The skeleton graph is cut at every edge that isn't between two members, so a
    window can never reach across a label boundary into another compartment. A
    non-member vertex is isolated and gets only its own value. Returned in
    positional order.
    """
    n = parent_array.shape[0]
    v = np.arange(n)
    edge = (v != root) & (parent_array >= 0)
    src, dst = v[edge], parent_array[edge]
    keep = member_mask[src] & member_mask[dst]
    src, dst = src[keep], dst[keep]
    ones = np.ones(src.size)
    B = sparse.csr_matrix(
        (
            np.concatenate([ones, ones]),
            (np.concatenate([src, dst]), np.concatenate([dst, src])),
        ),
        shape=(n, n),
    )
    step = sparse.identity(n, format="csr") + B
    reach = sparse.identity(n, format="csr")
    for _ in range(int(window_hops)):
        reach = reach @ step
        reach.data = np.ones_like(reach.data)  # set-reachability, not path counts
    return np.asarray(reach @ np.asarray(values, dtype=float)).ravel()


@dataclass
class RootDecision:
    """The outcome of :func:`root_policy` -- a pure decision plus its audit.

    Holds where to root (``root``, positional) and which classes the root may take
    (``root_classes``, to feed :meth:`TransitionSchema.with_root_classes`), along
    with the evidence behind the call so a dataset can be swept before committing.
    Nothing is mutated until :meth:`apply` is called.
    """

    root: int
    root_classes: List
    rerooted: bool
    reason: str
    old_root: int
    root_class: object
    window_logodds: float
    old_window_logodds: float
    span_size: int
    n_qualifying_spans: int

    def apply(self, cell: Cell) -> Cell:
        """Commit the decision: reroot the cell's skeleton if it changed.

        Returns the (mutated) cell for chaining. Build the decode schema with
        ``schema.with_root_classes(decision.root_classes)``; this method only
        moves the skeleton root.
        """
        if self.rerooted:
            cell.skeleton.reroot(int(self.root), as_positional=True)
        return cell

    def __str__(self) -> str:
        head = "reroot" if self.rerooted else "keep"
        move = f"{self.old_root} -> {self.root}" if self.rerooted else f"{self.root}"
        return (
            f"RootDecision({head} {move}; root_classes={self.root_classes}; "
            f"window_logodds={self.window_logodds:.2f}; {self.reason})"
        )


def root_policy(
    cell: Cell,
    labeler: "StructuredLabeler",
    *,
    root_class="dendrite",
    unaries: Optional[np.ndarray] = None,
    has_nucleus: Optional[bool] = None,
    nucleus_root: Optional[int] = None,
    window_hops: int = 5,
    min_window_logodds: float = 10.0,
    fallback_root_classes: Sequence = ("axon",),
    root_score: Optional[np.ndarray] = None,
) -> RootDecision:
    """Decide where to root a cell for the structured decode (no mutation).

    The decode's directional priors are root-relative, so the root must sit in a
    genuine ``root_class`` region. Evidence is measured in **log-odds, local to
    the candidate root and confined to its component**: the per-vertex margin
    ``u[root_class] - max(u[other])`` (nats, same units as the schema's transition
    costs), summed over each candidate's ``window_hops``-hop neighborhood *within
    its own connected span of root_class-dominant vertices* -- the window is cut
    at the span boundary, so it never accumulates across into axon. A vertex
    qualifies as a root only when that on-component windowed sum clears
    ``min_window_logodds``; summing (not averaging) requires a genuine local span
    of supporting evidence rather than a lone high-margin spike. The decision is
    conservative and a-priori first:

    1. **Nucleus present** (``has_nucleus`` true and ``nucleus_root`` given) ->
       trust it: root at the soma node, ``root_classes=[root_class]``.
    2. Else compute the on-component windowed margin and the connected components
       (the *spans*) holding any vertex that clears ``min_window_logodds``. If the
       **current root already qualifies**, keep it (no gratuitous re-rooting). If
       not but some vertex qualifies, **re-root** to the qualifying vertex of
       highest ``root_score`` (default: the windowed margin itself). If **nothing
       qualifies**, treat the cell as a terminal fragment: keep the current root
       and return ``fallback_root_classes``.

    Parameters
    ----------
    cell : Cell
        Must have a rooted skeleton; topology is read, never changed.
    labeler : StructuredLabeler
        Supplies the encoder (for unaries, when ``unaries`` is not given) and the
        schema (for class order). ``root_class`` must be one of its classes.
    root_class : hashable
        The anchor class a real root should belong to (e.g. ``"dendrite"`` or, for
        a K>2 schema, ``"soma"``).
    unaries : np.ndarray, optional
        Precomputed ``(n_vertices, K)`` log-potentials in ``schema.classes`` order.
        When omitted, ``labeler.predict_unaries(cell)`` is used. Pass this to sweep
        a dataset without re-running the encoder.
    has_nucleus, nucleus_root : optional
        A-priori soma evidence. ``nucleus_root`` is a positional vertex index.
    window_hops : int
        Topological radius of the on-component neighborhood the margin is summed
        over -- the local window around each candidate root (same hop notion the
        encoder's feature aggregation uses, not a metric distance). Larger windows
        sum more vertices, so calibrate ``min_window_logodds`` alongside it.
    min_window_logodds : float
        Threshold (nats) on the on-component windowed *sum* of the margin for a
        vertex to be a convincing root. Calibrate against the schema's transition
        costs and ``window_hops`` via a dry-run sweep.
    fallback_root_classes : sequence
        ``root_classes`` to return when nothing qualifies (terminal fragment).
    root_score : np.ndarray, optional
        ``(n_vertices,)`` score maximized to pick the root among qualifying
        vertices; defaults to the windowed margin. Pass e.g. ``windowed_margin *
        radius`` to prefer the high-radius soma over thin proximal dendrite.

    Returns
    -------
    RootDecision
        The chosen root, ``root_classes``, and audit. Mutates nothing; call
        :meth:`RootDecision.apply` to commit.
    """
    skel = cell.skeleton
    classes = list(labeler.schema.classes)
    if root_class not in classes:
        raise ValueError(
            f"root_class {root_class!r} is not in schema.classes {classes}."
        )
    col = classes.index(root_class)

    if unaries is None:
        unaries = labeler.predict_unaries(cell)
    unaries = np.asarray(unaries, dtype=float)

    # Per-vertex one-vs-best margin for root_class (nats). Members are the vertices
    # where root_class wins; sum the margin over each member's hop-window confined
    # to its own member component (cut at the boundary, so no axon bleed-in).
    other = np.delete(unaries, col, axis=1).max(axis=1)
    margin = unaries[:, col] - other
    pa = np.asarray(skel.parent_node_array)
    old_root = int(skel.root_positional)
    member_mask = margin > 0
    windowed = _oncomponent_window_sum(pa, old_root, member_mask, margin, window_hops)

    old_lo = float(windowed[old_root])
    score = windowed if root_score is None else np.asarray(root_score, dtype=float)

    # 1. Nucleus a-priori: trust the soma node.
    if has_nucleus and nucleus_root is not None:
        nucleus_root = int(nucleus_root)
        return RootDecision(
            root=nucleus_root,
            root_classes=[root_class],
            rerooted=nucleus_root != old_root,
            reason="nucleus present; rooted at soma",
            old_root=old_root,
            root_class=root_class,
            window_logodds=float(windowed[nucleus_root]),
            old_window_logodds=old_lo,
            span_size=-1,
            n_qualifying_spans=-1,
        )

    # 2. Qualifying spans: member components holding a vertex whose on-component
    #    windowed margin clears the threshold.
    qualify = windowed >= min_window_logodds
    comp = _tree_mask_components(pa, old_root, member_mask)
    n_qual = int(np.unique(comp[qualify & (comp >= 0)]).size)

    # 2a. Nothing qualifies -> terminal fragment, keep current root.
    if n_qual == 0:
        return RootDecision(
            root=old_root,
            root_classes=list(fallback_root_classes),
            rerooted=False,
            reason=(
                f"no {root_class} window >= {min_window_logodds:g} nats; "
                "terminal fragment"
            ),
            old_root=old_root,
            root_class=root_class,
            window_logodds=old_lo,
            old_window_logodds=old_lo,
            span_size=0,
            n_qualifying_spans=0,
        )

    # 2b. Current root already qualifies -> trust it.
    if qualify[old_root]:
        return RootDecision(
            root=old_root,
            root_classes=[root_class],
            rerooted=False,
            reason=f"current root already in a convincing {root_class} window",
            old_root=old_root,
            root_class=root_class,
            window_logodds=old_lo,
            old_window_logodds=old_lo,
            span_size=int(np.sum(comp == comp[old_root])),
            n_qualifying_spans=n_qual,
        )

    # 2c. Re-root to the highest-scoring qualifying vertex.
    cand = np.flatnonzero(qualify)
    new_root = int(cand[np.argmax(score[cand])])
    return RootDecision(
        root=new_root,
        root_classes=[root_class],
        rerooted=new_root != old_root,
        reason=(
            f"current root window={old_lo:.2f} nats below {min_window_logodds:g}; "
            f"rerooted to {root_class} window of {float(windowed[new_root]):.2f} nats"
        ),
        old_root=old_root,
        root_class=root_class,
        window_logodds=float(windowed[new_root]),
        old_window_logodds=old_lo,
        span_size=int(np.sum(comp == comp[new_root])),
        n_qualifying_spans=n_qual,
    )
